# Generated by Django 5.2.5 on 2025-09-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting_app', '0003_companytype_product_module_estimate'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='branches_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of Branches'),
        ),
    ]
