# Generated by Django 5.2.5 on 2025-09-03 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting_app', '0004_estimate_branches_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimate',
            name='branches_no',
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='location',
        ),
        migrations.AlterField(
            model_name='module',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='consulting_app.product'),
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='consulting_app.estimate')),
            ],
        ),
    ]
