# Generated by Django 5.2.5 on 2025-09-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting_app', '0005_remove_estimate_branches_no_remove_estimate_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
