# Generated by Django 5.2.5 on 2025-09-05 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting_app', '0006_estimate_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='demo_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='timeline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
