# Generated by Django 5.2.5 on 2025-09-05 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting_app', '0007_estimate_demo_date_estimate_timeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='cost_per_day',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='module',
            name='functional_days',
            field=models.PositiveIntegerField(default=0, help_text='Functional effort in days'),
        ),
        migrations.AddField(
            model_name='module',
            name='technical_days',
            field=models.PositiveIntegerField(default=0, help_text='Technical effort in days'),
        ),
        migrations.CreateModel(
            name='SubModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submodules', to='consulting_app.module')),
            ],
        ),
    ]
