# Generated by Django 5.2.5 on 2025-09-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting_app', '0008_module_cost_per_day_module_functional_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='submodule',
            field=models.ManyToManyField(blank=True, to='consulting_app.submodule'),
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='module',
        ),
        migrations.AddField(
            model_name='estimate',
            name='module',
            field=models.ManyToManyField(blank=True, to='consulting_app.module'),
        ),
    ]
