# Generated by Django 5.2.5 on 2025-09-05 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting_app', '0009_estimate_submodule_remove_estimate_module_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimate',
            name='submodule',
        ),
        migrations.RemoveField(
            model_name='module',
            name='cost_per_day',
        ),
        migrations.AddField(
            model_name='estimate',
            name='submodules',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='subsubmodules',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='module',
        ),
        migrations.AlterField(
            model_name='module',
            name='functional_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='module',
            name='technical_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SubSubModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('submodule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsubmodules', to='consulting_app.submodule')),
            ],
        ),
        migrations.AddField(
            model_name='estimate',
            name='module',
            field=models.TextField(blank=True, null=True),
        ),
    ]
