# Generated by Django 5.2.5 on 2025-09-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting_app', '0010_remove_estimate_submodule_remove_module_cost_per_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='final_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='estimate',
            name='functional_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='estimate',
            name='functional_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estimate',
            name='technical_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='estimate',
            name='technical_days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
